version: "3"
services:
  data_python_generator:
    build:
      dockerfile: ./opcuapy/Dockerfile
    container_name: opc_py_data_generator
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "4840:4840"

  data_js_generator:
    build:
      dockerfile: ./opcuajs/Dockerfile
    container_name: opc_js_data_generator
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "4841:4841"

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto 
    ports:
      - 1883:1883
      - 8883:8883
      - 9001:9001
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
    networks:
      - mosquitto

  maccor:
    build:
      dockerfile: ./maccor/Dockerfile
    container_name: maccor
    ports:
      - "7889:7889"
      - "7890:7890"
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - mosquitto

networks:
    mosquitto:
        name: mosquitto
        driver: bridge
