version: '3'
services:
  data_python_generator:
    build:
      dockerfile: ./opcuapy/Dockerfile
    container_name: opc_py_data_generator
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "4840:4840"

  data_js_generator:
    build:
      dockerfile: ./opcuajs/Dockerfile
    container_name: opc_js_data_generator
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    ports:
      - "4841:4841"   

  mqtt_broker:
    build:
      dockerfile: ./mqtt/Dockerfile
    container_name: mqtt_broker
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
